# Generated by Django 5.2.3 on 2025-06-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernutrition',
            name='goal_calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usernutrition',
            name='goal_carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usernutrition',
            name='goal_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usernutrition',
            name='goal_protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usernutrition',
            name='goal_water',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrition',
            name='total_calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrition',
            name='total_carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrition',
            name='total_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrition',
            name='total_protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrition',
            name='total_water',
            field=models.FloatField(default=0),
        ),
    ]
