# Generated by Django 5.2.3 on 2025-06-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_usernutrition_goal_calories_usernutrition_goal_carbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernutrition',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
