# Generated by Django 5.2.3 on 2025-07-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_usernutrition_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_meals', to='Users.user'),
        ),
    ]
