# Generated by Django 5.2.3 on 2025-07-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_meal_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='creator',
        ),
    ]
