# Generated by Django 5.2.3 on 2025-07-01 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_meal_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernutrition',
            name='meals',
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='usernutrition',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_profile', to='Users.user'),
        ),
        migrations.CreateModel(
            name='CustomMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('fats', models.FloatField()),
                ('carbs', models.FloatField()),
                ('water', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='custom_meal_pics/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_meals', to='Users.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
